apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nlweb-tls-cert
  namespace: gateway
spec:
  secretName: nlweb-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - ${HOSTNAME}
