apiVersion: v1
kind: Service
metadata:
  name: {{ include "crawler.masterServiceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "crawler.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "crawler.masterSelectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.master.port }}
      targetPort: {{ .Values.master.port }}
      protocol: TCP
