apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crawler.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    azure.workload.identity/client-id: {{ required "workloadIdentity.clientId is required" .Values.workloadIdentity.clientId | quote }}
  labels:
    {{- include "crawler.labels" . | nindent 4 }}
