{{- if .Values.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ask-api.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    azure.workload.identity/client-id: {{ required "workloadIdentity.clientId is required" .Values.workloadIdentity.clientId | quote }}
  labels:
    azure.workload.identity/use: "true"
    {{- include "ask-api.labels" . | nindent 4 }}
{{- end }}
