apiVersion: v1
kind: Service
metadata:
  name: {{ include "chat-app.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chat-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "chat-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
